apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.config.name }}"
  labels:
    app: "{{ .Values.config.name }}"
  namespace: {{ .Values.config.namespace }}
spec:
  replicas: {{ .Values.config.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.config.name }}"
  template:
    metadata:
      annotations:
        {{- if .Values.config.vault }}
          vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
          vault.security.banzaicloud.io/vault-tls-secret: vault-tls
          vault.security.banzaicloud.io/vault-role: "{{ .Values.config.name }}"
          vault.security.banzaicloud.io/vault-env-from-path: "secret/data/{{ .Values.config.vaultpath }}"
        {{- end }}
      labels:
        app: "{{ .Values.config.name }}"
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always

          {{- if .Values.env.envFromSecretUse }}
          envFrom:
          - secretRef:
              name: {{ .Values.env.envFromSecret }}
          {{- end }}
          env:
            {{- range .Values.env.env_config }}
            - name: {{ .name }}
              value: {{ .value | quote  }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
