{{- if .Values.ingresPrivate }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
  name: "{{ .Values.config.name }}-ingress"
spec:
  rules:
  - host: "{{ .Values.ingresPrivateConfig.DomainName }}"
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.config.name }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: ImplementationSpecific
        
{{- end }}
