FROM node:lts-alpine as builder

WORKDIR /app

COPY . /app

RUN npm install

RUN npm run build


FROM nginx:alpine 

COPY nginx/default.conf /etc/nginx/conf.d/

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist/console/browser /usr/share/nginx/html

CMD [ "nginx", "-g","daemon off;"]