apiVersion: v1
data:
  admin.password: 
  admin.passwordMtime: 
  oidcClientSecret: 
  server.secretkey: 
  tls.crt: 
  tls.key: 
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
